- uses: actions/checkout@v3

- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ${{ secrets.AWS_REGION }}

- name: Log in to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v2

- name: Build, tag, and push Docker image to ECR
  id: build-image
  run: |
    set -e
    IMAGE_TAG=${GITHUB_SHA::8}
    REGISTRY=${{ steps.login-ecr.outputs.registry }}
    REPOSITORY=${{ secrets.ECR_REPOSITORY }}
    IMAGE_URI=${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

    echo "Registry: $REGISTRY"
    echo "Repository: $REPOSITORY"
    echo "Image URI: $IMAGE_URI"

    docker build -t $IMAGE_URI .
    docker push $IMAGE_URI

    # Save full image URI (one line) for CD to read
    echo $IMAGE_URI > latest_image.txt

- name: Commit latest image file (optional)
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add latest_image.txt || true
    git commit -m "chore: update latest_image.txt" || true
    git push origin main || echo "push failed (token perms?)"
