name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Terraform Init
      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      # 4. Terraform Plan
      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${GITHUB_SHA::8}" \
          -var="key_name=your-keypair-name"

      # 5. Terraform Apply
      - name: Terraform Apply
        working-directory: ./Terraform
        run: terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${GITHUB_SHA::8}" \
          -var="key_name=your-keypair-name"
