name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: latest-image
          path: ./artifact

      - name: Read image URI
        run: |
          IMAGE_URI=$(cat artifact/latest_image.txt)
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.9

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: ./terraform
        env:
          ECR_IMAGE_URI: ${{ env.IMAGE_URI }}
        run: |
          terraform apply -auto-approve -input=false -var="ecr_image_uri=${ECR_IMAGE_URI}"
