name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣heckout code
      - uses: actions/checkout@v3

      # 2️⃣onfigure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # 4️⃣ebug Terraform installation
      - name: Check Terraform
        run: terraform version

      # 5️⃣et IMAGE_TAG variable
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 6️⃣erraform Init
      - name: Terraform Init
        working-directory: ./strapi-terraform/terraform
        run: terraform init

      # 7️⃣erraform Plan
      - name: Terraform Plan
        working-directory: ./strapi-terraform/terraform
        run: terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="key_name=your-keypair-name"

      # 8️⃣erraform Apply
      - name: Terraform Apply
        working-directory: ./strapi-terraform/terraform
        run: terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="key_name=your-keypair-name"
