name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform manually
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform version

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./strapi-terraform/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./strapi-terraform/terraform
        run: terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="key_name=your-keypair-name"

      - name: Terraform Apply
        working-directory: ./strapi-terraform/terraform
        run: terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ecr_registry=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" \
          -var="ecr_repository=${{ secrets.ECR_REPOSITORY }}" \
          -var="image_tag=${{ env.IMAGE_TAG }}" \
          -var="key_name=your-keypair-name"
